version: "3.1"

services:

  web:
    image: carrievrtis:app
    dns:
      - 9.9.9.9
      - 208.67.222.222
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - SERVER_LISTEN_PORT=8080
    secrets:
      - recaptcha
    volumes:
      - "./app:/app"
    working_dir: /app
    command: ["./startup.sh"]
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

secrets:
  recaptcha:
    file: ./secrets/recaptcha.json

networks:
  backend:
