version: "3.1"

services:

  web:
    image: carrievrtis:app
    volumes:
      - "./app:/app"
    working_dir: /app
    dns:
      - 9.9.9.9
      - 208.67.222.222
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - SERVER_LISTEN_PORT=8080
    secrets:
      - recaptcha
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    image: carrievrtis:nginx
    volumes:
      - "./nginx/config:/config"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    environment:
      - URL=carrievrtis.com
      - SUBDOMAINS=www,ftp,mail
      - VALIDATION=http
      - TZ=America/Los_Angeles
      - PGID=1000
      - PUID=1000
      - EMAIL=cjvrtis@gmail.com
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

secrets:
  recaptcha:
    file: ./secrets/recaptcha.json

networks:
  backend:
