version: "3.1"

services:

  web:
    image: carrievrtis:app
    volumes:
      - "./app:/app"
    working_dir: /app
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - backend
    environment:
      - SERVER_LISTEN_PORT=8080
    secrets:
      - recaptcha
    deploy:
      replicas: 2
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 3
        window: 120s

secrets:
  recaptcha:
    file: ./secrets/recaptcha.json

networks:
  backend:
